### ISSUE TITLE
Disable “perspective zoom” (parallax)

### ISSUE THREAD

**Issue by illixion** [MichaelMKenny/ios-13-light-dark-wallpaper-app#1]
Could you please compile a version of this app that doesn’t enable parallax on wallpapers, or possibly add a switch for toggling this behavior? I'm really enjoying your app, but I wish it didn’t cut off parts of my wallpaper because of this. Best regards.

**Comment by MichaelMKenny** [comment]
Thanks, I would like a toggle for this too. It was the first thing I noticed once I built on to my phone.

I think it's something I have configure in `SBFWallpaperOptions`.
