### ISSUE TITLE
Can't display Set Wallpaper

### ISSUE THREAD

**Issue by invalidunit** [MichaelMKenny/ios-13-light-dark-wallpaper-app#5]
When I open "Set Wallpaper.app" with iPhone SE, I cannot see and cannot click the "Set Wallpaper" button to set the wallpaper
But "Set Wallpaper.app" works fine on iPhone 7
![32ABB90B61F8FFCD1164CA28C704FE62](https://user-images.githubusercontent.com/35675770/73069270-48076380-3ee8-11ea-807c-26e8ae72b04c.png)

**Comment by MichaelMKenny** [comment]
I wondered if the SE screen size would be an issue. I use an iPhone X so everything fits. Thanks for letting me know :) I'll try and optimize the layout to fit on the SE sometime soon.

**Comment by MichaelMKenny** [comment]
Sorry I forgot to mention this issue's number in the commit that fixes this ¯\_(ツ)_/¯. Anyway, this issue is resolved :)
